pipeline{
    agent any
    tools{
        jdk 'jdk17'
        nodejs 'node16'
        dotnetsdk '.net'
    }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage('Clean Workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/ajaydabe/Tetris-gamev1.git'
            }
        }
        stage("Sonarqube Analysis "){
            steps{
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=TetrisVersion1.0 \
                    -Dsonar.projectKey=TetrisVersion1.0 '''
                }
            }
        }
        stage("Quality Gate"){
           steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            } 
        }
        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }
        stage('OWASP FS Scan') {
            steps {
                withEnv(['JAVA_OPTS=-Xmx6g']) {
                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                }
            }
        }
        stage('TRIVY FS Scan') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        stage("Docker Build Image"){
            steps{
                sh "docker build -t tetrisv1 ."
                sh "docker tag tetrisv1 ajaydabe/tetrisv1:latest"
            }
        }
        stage ('Docker Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                    sh 'docker push ajaydabe/tetrisv1:latest'
                }
            }
        }
        stage("TRIVY Image Scan"){
            steps{
                sh "trivy image ajaydabe/tetrisv1:latest > trivyimage.txt" 
            }
        }
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ajaydabe/tetris-deployment.git'
            }
        }

        stage('Update Deployment File') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    // Determine the image name dynamically based on your versioning strategy
                    NEW_IMAGE_NAME = "ajaydabe/tetrisv1:latest"

                    // Replace the image name in the deployment.yaml file
                    sh "sed -i 's|image: .*|image: $NEW_IMAGE_NAME|' deployment.yml"

                    // Git commands to stage, commit, and push the changes
                    sh 'git add deployment.yml'
                    sh "git commit -m 'Update deployment image to $NEW_IMAGE_NAME'"
                    sh "git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main"
                    }
                }
            }
        }
    }
}
